name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: 21
          distribution: 'adopt'
          cache: gradle
      - name: Apply Spotless
        run: ./gradlew spotlessApply
      - name: Gradle Build
        run: ./gradlew build
      - name: Gradle Tests
        run: ./gradlew test